cmd/pmm-managed/main.go
handlers/alerts.go
handlers/scrape_jobs.go
services/prometheus/alerts.go
services/prometheus/base.go
services/prometheus/config.go
services/prometheus/prometheus_test.go
services/prometheus/scrape_jobs.go
testdata/prometheus/prometheus.yml

Unfortunately, I had to copy a file from Prometheus and then patch it to remove special handling of secrets (passwords, etc.)
@arvenil @percona-csalguero Can you think of a better way?
@vadimtk Can we do it this way from the legal point of view: https://github.com/percona/pmm-managed/pull/4/files#diff-da7d8cce99d3a7aa636ac4f714f624fe ?

Handle Prometheus config with secrets

---

services/prometheus/scrape_configs.go

It happens when exporter is reachable, but returns
HTTP code other than 200. Typically it is 404 if
metrics path is incorrect.

PMM-2090 Fix external exporters add deadlock.

---

services/rds/rds.go

Always use `instance` label values from exporters. See `honor_labels` [here](https://prometheus.io/docs/prometheus/1.8/configuration/configuration/#<scrape_config>).

PMM-2155 Honor instance labels for RDS.

---

services/mysql/mysql.go
services/mysql/mysql_test.go
services/postgresql/postgresql.go
services/postgresql/postgresql_test.go

Set default port for MySQL and PostgreSQL if port is not presented in Add request.

PMM-3061 Set default port

---

services/mysql/mysql.go
services/postgresql/postgresql.go

Got this error on initialize if user has added PostgreSQL or MySQL instance and restarted pmm-server.
msg="PostgreSQL service problem: sql: no rows in result set\ngithub.com/percona/pmm-managed/services/mysql.(*Service).ApplyPrometheusConfiguration\n\t/home/builder/rpm/BUILD/pmm-managed-a9633ca109431f724c1a69427194c1117a83aca5/src/github.com/percona/pmm-managed/services/mysql/mysql.go:140"

PMM-3061 Fixed service not found error

---

services/mysql/mysql.go
services/mysql/mysql_test.go
services/postgresql/postgresql.go
services/postgresql/postgresql_test.go

Trimmed values for address, username and name parameters in Add request

PMM-3190 Trim space in parameters value

---

models/agent_model.go
models/node_model.go
models/service_model.go
services/qan/client.go

PMM-3891 Set agent_id in QAN data.

---

.travis.yml

We still need builds for PMM-2.0 branch to calculate code coverage changes correctly: https://docs.codecov.io/docs/error-reference#section-missing-base-commit

Skip non-trunk PMM-XXXX branch builds.

---

services/checks/checks.go

To add spaces between arguments – something our logs depend on.

Use Debugln instead of Debug.

---

cmd/pmm-managed-starlark/main.go

The previous 100MB limit was causing intermittent errors "cannot allocate memory", for now we will bump the limit up to 1GB [link to slack conversation](https://percona.slack.com/archives/GV9GJJY77/p1601899214121300) and solve the problem later as a part of SAAS-372

SAAS-372 pmm-managed-starlark: Increase memory limit to 1GB

---

README.md
main.go
main_test.go
models/agent_model.go
models/node_model.go
models/service_model.go
models/settings.go
packages.dot
services/victoriametrics/alerting_rules.go
services/victoriametrics/alerting_rules_test.go
services/victoriametrics/prometheus.go
services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics.go
services/victoriametrics/vmalert.go
services/victoriametrics/vmalert_test.go

With only a minimal refactoring. In particular, many methods should be un-exported now, but that is delayed to make diff smaller.

Merge prometheus package into victoriametrics

---

.golangci.yml
main_test.go
services/vmalert/alerting_rules.go
utils/validators/alerting_rules.go
utils/validators/alerting_rules_test.go
utils/validators/validators.go

We need it for both integrated and external alerting, but `vmalert.AlertingRules` is very external-specific.
[PMM-6891](https://jira.percona.com/browse/PMM-6891)
---

PMM-6891 Extract alerting rule validation function

---

services/management/grpc/actions_server.go

Not sure why we don't return original error, but let's at least log it.

Log original error

---

services/agents/postgresql.go
services/agents/postgresql_test.go

After `auto-discover-databases` flag was added to the postgresql-exporter tests start failing with `pq: database "pmm-managed-dev" is being accessed by other users` error. So as temporary solution we can exclude our test db from discovery.
That PR CI fails because it uses previous image of PMM server.
---

Exclude test db from pg exporter

---

Makefile.devcontainer
docker-compose.yml

Dev command for attaching delve
Compile pmm-managed with extra debug flags
I'm not sure about `make install`:
It does `go install` with debugging flags
But then make release
Which creates binaries to PMM_RELEASE_PATH. But `make run` copy binary from this PMM_RELEASE_PATH, copy to /sbin and run it.
So I think, we don't use then binary with these extra flags

DLV Debugger

---

services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics_test.go
testdata/victoriametrics/promscrape.yml

[PMM-8145 Remote PostgreSQL instance is not displayed on dashboards (OVF) ](https://jira.percona.com/browse/PMM-8145)
---
**DRAFT** because we need the feasture build to test before we decide to merge this.

PMM-8145 Update scrape timeout for RDS

---

go.mod
go.sum
services/qan/client.go
services/supervisord/devcontainer_test.go

[PMM-8116](https://jira.percona.com/browse/PMM-8116)
https://github.com/percona/pmm/pull/743
https://github.com/percona/pmm-agent/pull/271
https://github.com/percona/qan-api2/pull/111
---

PMM-8116 New metrics for pg_stat_monitor 0.9.

---

services/checks/checks.go

Before: If `UpdateIntervals` is called before `s.startDelay`, it will panic.
It fixes also API tests.

Initialize tickers immediately

---

.github/workflows/ci.yml

Jobs started to fail constantly because of jobs execution timeout, so the quick fix is to increase the timeout to 30m.

Increase github jobs timeout

---

utils/envvars/parser.go
utils/envvars/parser_test.go

[PMM-9050](https://jira.percona.com/browse/PMM-9050)
This is a fix for a bug that makes pmm-managed crash when port is part of the SAAS host. We now can handle such state. Parsing out the host only.
---

PMM-9050 parseSAASHost: avoid including the port if it's passed

---

services/agents/mongodb.go
services/agents/mongodb_test.go
services/platform/platform.go
services/supervisord/supervisord.go
testdata/supervisord.d/grafana.ini
utils/envvars/parser.go
utils/envvars/parser_test.go
utils/saasreq/request.go

[PMM-9304](https://jira.percona.com/browse/PMM-9304) Disable dbstat and topmetrics for mongodb exporter in default mode for 2.25.0

PMM-9304 Disable dbstats & topmetrics

---

services/checks/registry.go

Make STT target label more prioritized against STT result labels. Otherwise, STT check can override service name, for example.
---

Keep STT target lables in priority

---

services/agents/mongodb.go
services/agents/mongodb_test.go

[PMM-9400](https://jira.percona.com/browse/PMM-9400) Missing metrics for indexStats and collStats when all collectors enabled
In order to make it work correctly, we need to pass `--mongodb.indexstats-colls=` also, not only `--mongodb.collstats-colls=`

PMM-9400 Added indexstats list

---

services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics_test.go

* PMM-8804 Remote PostgreSQL metrics are not being captured.
* PMM-8804 Fix tests.
* PMM-8804 Fix tests.
Cherry picked to include it to PMM 2.26
[PMM-8804](https://jira.percona.com/browse/PMM-8804)
---

PMM-8804 Remote PostgreSQL metrics are not being captured. (#973)

---

.github/workflows/ci.yml

Linters job sometimes fails because it runs +/- 10 min

Update timeout for 'Check' job

---

.github/workflows/ci.yml

Fuzzdata left after tests caused error during cache process. This PR fixes it.
Original issue: https://github.com/actions/cache/issues/753

Fix CI cache

---

.gitignore
api-tests/README.md
api-tests/server/logs_test.go
services/supervisord/logs_test.go

PMM-9863
Build: [SUBMODULES-2459](https://github.com/Percona-Lab/pmm-submodules/pull/2459)
Note: `TestZip` and `TestFiles` will fail before we merge peer PRs in `pmm-server` and `pmm-update`. Otherwise both tests pass in the feature build https://pmm.cd.percona.com/job/pmm2-api-tests/9777/consoleFull.

PMM-9863 remove yum-cron

---

api-tests/server/alertmanager_test.go
api-tests/server/helpers.go
api-tests/server/settings_test.go
models/database.go
models/settings.go
models/settings_helpers.go
models/settings_helpers_test.go
services/checks/checks.go
services/checks/checks_test.go
services/platform/platform.go
services/server/server.go

PMM-9841
SUBMODULES-2482
This turns on advisors by default in PMM. Instead of setting STTEnabled to true, it renames STTEnabled to STTDisabled (which is false by default). This is to avoid having to deal with boolean pointers (since we still need to detect "absent" vs "false" cases).
This doesn't need any corresponding frontend change to work but ideally, we could also update it to use the updated fields for consistency.

PMM-9841 enable advisors by default
