percona/pmm-managed

services/prometheus/base.go
services/prometheus/internal/config.go
services/prometheus/scrape_jobs.go

To reduce a number of identifiers exported by prometheus package.

Move Prometheus config into internal/.

---

models/agent.go
models/agent_reform.go
models/database.go
services/rds/rds.go
services/rds/rds_test.go

Do not pass -collect.info_schema.tablestats
to mysqld_exporter if there are more than 1000
tables.

PMM-2839 Add tablestats safety precaution.

---

services/rds/rds.go

PMM-2839 Fix tablestats safety precaution.

---

services/postgresql/postgresql.go

forgot to remove unnecessary printing credentials I made for debug reason

PMM-3075 hide credentials

---

Makefile
cmd/pmm-managed/maincover_test.go

#104 with a new ticket number.

PMM-3484 Implement `make run-race-cover`.

---

models/database.go
models/node.go
services/inventory/nodes.go

That was an old special case that is no longer used.

PMM-3626 Remove «pmm-server» Node type.

---

cmd/pmm-managed/main.go
services/mysql/mysql_test.go
services/rds/rds.go

add  aws cn region , or reject my PR and help to add support aws cn region.

PMM-3628 Update rds.go to add aws cn region

---

.travis.yml
docker-compose.yml
services/grafana/grafana_test.go
testdata/grafana/grafana.ini
testdata/grafana/provisioning/dashboards/Prometheus.json
testdata/grafana/provisioning/datasources/prometheus.yaml

* update image versions;
* update configuration;
* fix provisioning;
* update Prometheus dashboard.
Note that tests are skipped by 9bcc8acf814bdc11f2a131b3b6ab8380a09f4f59 due to authentication. That's https://jira.percona.com/browse/PMM-3812.

PMM-3672 Grafana update.

---

services/management/service.go

PMM-4200 Fix ProxySQL removal.

---

services/prometheus/prometheus.go
services/prometheus/prometheus_test.go
services/prometheus/scrape_configs.go
services/prometheus/scrape_configs_test.go

Reverts percona/pmm-managed#235

Revert "PMM-3643 Add collect query parameter to Prometheus configuration file generator."

---

models/agent_model.go
models/agent_model_test.go

Added TLS fields missed in previous PR

PMM-4663 Added TLS for agent_model

---

.devcontainer/install-dev-tools.sh
.golangci.yml
.travis.yml
services/server/server.go
services/supervisord/devcontainer_test.go
services/supervisord/logs.go
services/supervisord/logs_test.go

Add all logs from `/srv/logs` and missing config files.
Also remove a usage of `tail` via `exec.Command`. Read last lines with Go.

PMM-4733 Add missing files to logs.zip.

---

.travis.yml
services/mysql/mysql.go
services/qan/qan.go
services/rds/rds.go

https://jira.percona.com/browse/PMM-3089
FB: https://github.com/Percona-Lab/pmm-submodules/pull/509

PMM-3089 Restore qan-agent config.

---

services/qan/qan.go

https://jira.percona.com/browse/PMM-3089
https://github.com/Percona-Lab/pmm-submodules/pull/511

PMM-3089 Handle qan-agent settings for custom setup.

---

services/telemetry/telemetry.go

https://jira.percona.com/browse/PMM-4400
FB: Percona-Lab/pmm-submodules#514

PMM-4400 Read dist from file.

---

services/management/mysql.go

Updated tables count after checking the connection

PMM-5026 Fix table count results.

---

.travis.yml

Ran `go test -timeout=30s -p 1 -race ./...` locally with go 1.13.5 and all tests are passing

PMM-4010 Added Go 1.13.x to Travis

---

Gopkg.lock
Gopkg.toml
services/prometheus/internal/README.md
services/prometheus/internal/common/config/http_config.go
vendor/github.com/percona/exporter_shared/helpers/collect.go
vendor/github.com/percona/exporter_shared/helpers/format.go
vendor/github.com/percona/exporter_shared/helpers/metric.go

Update transitive Prometheus dependency `github.com/prometheus/common`
Feature build: https://github.com/Percona-Lab/pmm-submodules/pull/715

PMM-5464 Update prometheus dependencies

---

services/prometheus/prometheus.go
services/prometheus/prometheus_test.go
services/server/server_test.go

https://github.com/Percona-Lab/pmm-submodules/pull/722

PMM-5478 Fix Prometheus 1.16 config generation.

---

models/database.go
models/settings.go
models/settings_helpers_test.go
services/prometheus/prometheus_test.go
testdata/prometheus/prometheus.yml

FB: https://github.com/Percona-Lab/pmm-submodules/pull/733

PMM-5448 Changed default resolution

---

services/telemetry/telemetry.go

- https://jira.percona.com/browse/SAAS-73
That PR simplifies local testing. 
FB: https://github.com/Percona-Lab/pmm-submodules/pull/861

SAAS-73 Improve debug logging

---

services/checks/checks_test.go

- https://jira.percona.com/browse/SAAS-134

SAAS-134 Test that findTargets function skips pmm postgreSQL instance

---

Gopkg.lock
services/checks/checks.go
services/checks/checks_test.go

**Not for 2.7.0.**
- https://jira.percona.com/browse/SAAS-126
Minor fixes for https://github.com/percona/pmm-managed/pull/400
FB: https://github.com/Percona-Lab/pmm-submodules/pull/886

SAAS-126 MongoDB action minor changes

---

Gopkg.lock
services/checks/checks.go
services/checks/checks_test.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go

[SAAS-104](https://jira.percona.com/browse/SAAS-104)
---
---
Adds prometheus metrics for the checks service to record the number of check scripts executed and the number of alerts generated.

SAAS-104 Basic Prometheus Metrics for STT

---

services/agents/mongodb.go
services/agents/mongodb_test.go

[PMM-6435](https://jira.percona.com/browse/PMM-6435)
---

PMM-6435 Add flag to mongdb exporter --mongodb.global-conn-pool

---

main.go
services/prometheus/alerting_rules_test.go

[PMM-4597](https://jira.percona.com/browse/PMM-4597)
---

PMM-4597 Add a feature flag for nicer APIs

---

models/settings_helpers.go
services/server/server_test.go
utils/envvars/parser.go

No Jira task :)
Only this PR
---

Fix DBaaS feature flag reset.

---

services/checks/checks.go
services/checks/checks_test.go
services/platform/platform.go
services/telemetry/telemetry.go
services/telemetry/telemetry_test.go
utils/dial/dial.go
utils/saasdial/auth.go
utils/saasdial/dial.go

[SAAS-320](https://jira.percona.com/browse/SAAS-320)
---

SAAS-320 Add session ID to all requests

---

Gopkg.lock
Gopkg.toml

* https://github.com/percona/pmm/pull/595
* https://github.com/percona/pmm-managed/pull/492
* https://github.com/percona/pmm-agent/pull/199
https://github.com/Percona-Lab/pmm-submodules/pull/1180
Safe for the patch release

PMM-6760 Update protobuf

---

main.go

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)
---

PMM-6782 Fix High CPU usage.

---

services/server/deps.go
services/server/mock_supervisord_service_test.go
services/server/server.go
services/supervisord/devcontainer_test.go
services/supervisord/logs.go
services/supervisord/pmm_update_checker.go
services/supervisord/supervisord.go

[PMM-5823](https://jira.percona.com/browse/PMM-5823)
---

PMM-5823 unblock /version and /logs.zip endpoints.

---

Gopkg.lock
services/management/dbaas/xtradb_cluster_service_test.go

[PMM-6826](https://jira.percona.com/browse/PMM-6826)
---

PMM-6826 Fix tests.

---

Gopkg.toml
main.go
services/prometheus/alerting_rules.go
services/victoriametrics/victoriametrics.go

[PMM-7011](https://jira.percona.com/browse/PMM-7011)

PMM-7011 Add TODOs

---

models/channel_helpers.go
models/channel_helpers_test.go

[PMM-6968](https://jira.percona.com/browse/PMM-6968)
---

PMM-6968 Fix bug with missing update of channel's disabled flag

---

data/iatemplates/mysql_down.yml
data/iatemplates/mysql_restarted.yml
data/iatemplates/mysql_too_many_connections.yml

[PMM-7024](https://jira.percona.com/browse/PMM-7024)
They are not being used yet, but we need to start somewhere to unblock future work.

PMM-7024 Add built-in IA templates

---

models/channel_helpers.go
models/database.go
services/management/ia/alerts_service.go
services/management/ia/rules_service.go

[PMM-7207](https://jira.percona.com/browse/PMM-7207)
* https://github.com/Percona-Lab/pmm-api-tests/pull/157
---

PMM-7207 Toggle Rule API

---

models/database.go

[PMM-7212](https://jira.percona.com/browse/PMM-7212)
---

PMM-7212 Remove foreign key constraint from ia_rules table

---

Gopkg.lock
Gopkg.toml
vendor/github.com/percona/pmm/api/serverpb/server.pb.go

Fixing due to an invalid merge.

PMM-6944 Fixed dep version

---

services/management/ia/templates_service.go
services/management/ia/templates_service_test.go

[PMM-7023](https://jira.percona.com/browse/PMM-7023)
---

PMM-7023 Validate template prefixes

---

Gopkg.lock
models/models.go
models/rule_helpers.go
models/rule_helpers_test.go
models/template_helpers.go
models/template_helpers_test.go
services/alertmanager/alertmanager_test.go
services/management/ia/common.go
services/management/ia/rules_service.go
services/management/ia/rules_service_test.go
services/management/ia/templates_service.go
utils/tests/id.go
vendor/github.com/percona-platform/saas/pkg/common/severity.go

[PMM-7228](https://jira.percona.com/browse/PMM-7228)
https://github.com/Percona-Lab/pmm-api-tests/pull/165
---

PMM-7228 Fix severities and rule toggling

---

services/supervisord/supervisord.go
testdata/supervisord.d/victoriametrics.ini

[PMM-7141](https://jira.percona.com/browse/PMM-7141)
---

PMM-7141 Fix graphs delay.

---

models/template_helpers.go
models/template_helpers_test.go

[PMM-6941](https://jira.percona.com/browse/PMM-6941)
---

PMM-6941 More descriptive error message

---

models/agent_helpers.go
services/management/management.go

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)
---

PMM-7145 Change errors to grpc errors.

---

services/agents/registry.go
services/inventory/agents.go
services/inventory/agents_test.go
services/inventory/deps.go
services/inventory/mock_agents_registry_test.go
services/management/deps.go
services/management/external.go
services/management/mock_agents_registry_test.go
services/management/mongodb.go
services/management/mysql.go
services/management/postgresql.go
services/management/proxysql.go
services/management/rds.go
services/management/rds_test.go
services/management/service.go
services/management/service_test.go

[PMM-7426](https://jira.percona.com/browse/PMM-7426)
---

PMM-7426 Fix state change stuck.

---

services/management/haproxy.go

[PMM-6640](https://jira.percona.com/browse/PMM-6640)
---

PMM-6640 Fix for add_node property in HAProxy.

---

services/management/ia/rules_service_test.go
services/management/ia/templates_service.go

[PMM-7467](https://jira.percona.com/browse/PMM-7467)
https://github.com/Percona-Lab/pmm-api-tests/pull/182
---

PMM-7467 Fix bug with angle brackets escaping in rule expressions

---

Gopkg.toml

It was already removed from Gopkg.lock

Removed exporter_shared from Gopkg.toml

---

services/grafana/auth_server.go

[PMM-6766](https://jira.percona.com/browse/PMM-6766)
---

PMM-6766 Remove QAN App.

---

services/server/deps.go
services/server/mock_alertmanager_service_test.go
services/server/server.go
services/server/server_test.go

[PMM-7591](https://jira.percona.com/browse/PMM-7591)
---

PMM-7591 Fix alertmanager configuration updates

---

services/supervisord/supervisord.go
testdata/supervisord.d/victoriametrics.ini

[PMM-7635](https://jira.percona.com/browse/PMM-7635)
---

PMM-7635 Fix Victoria Metrics High CPU Usage.

---

main.go
services/grafana/auth_server.go

[PMM-7635](https://jira.percona.com/browse/PMM-7635)
---

PMM-7635 Reduce requests amount to grafana server.

---

services/management/dbaas/components_service.go

[PMM-7808](https://jira.percona.com/browse/PMM-7808)
---

PMM-7808 Fix response for PXC components.

---

Gopkg.lock
services/management/dbaas/components_service.go
services/management/dbaas/components_service_test.go
vendor/github.com/hashicorp/go-version/LICENSE
vendor/github.com/hashicorp/go-version/constraint.go
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_collection.go

[PMM-7779](https://jira.percona.com/browse/PMM-7779)
It's based on #706.
---

PMM-7779 remove old database server versions

---

services/agents/postgresql.go
services/agents/postgresql_test.go
services/agents/registry.go

[PMM-7345](https://jira.percona.com/browse/PMM-7345)
---

PMM-7345 Fix postgres_exporter for old clients.

---

go.mod
go.sum
services/dbaas/dbaas_client.go
services/management/dbaas/deps.go
services/management/dbaas/kubernetes_server.go
services/management/dbaas/kubernetes_server_test.go
services/management/dbaas/mock_dbaas_client_test.go
services/management/dbaas/psmdb_cluster_service_test.go
services/management/dbaas/xtradb_cluster_service_test.go

[PMM-6432](https://jira.percona.com/browse/PMM-6432)
https://github.com/Percona-Lab/pmm-submodules/pull/1773
https://github.com/percona-platform/dbaas-controller/pull/184
https://github.com/percona/pmm-managed/pull/758
https://github.com/percona-platform/dbaas-api/pull/126
---

PMM-6432 install kubernetes operators

---

services/management/service.go
services/management/service_test.go

[PMM-8121](https://jira.percona.com/browse/PMM-8121)
It would be better, if this was handle by pmm-admin. But our CLI parser (kingpin) doesn't support exclusive mutual groups.
- API tests: https://github.com/Percona-Lab/pmm-api-tests/pull/218
---

PMM-8121 Improved error message for remove service

---

services/management/rds_test.go

[PMM-8148](https://jira.percona.com/browse/PMM-8148)
---

PMM-8148 Fix test for RDS.

---

docker-compose.yml
services/agents/registry.go

[PMM-8123](https://jira.percona.com/browse/PMM-8123)
[PMM-8132](https://jira.percona.com/browse/PMM-8132)
---

PMM-8123 Fix race condition after upgrade.

---

docker-compose.yml
services/agents/registry.go
services/victoriametrics/scrape_configs.go
services/victoriametrics/victoriametrics_test.go
testdata/victoriametrics/promscrape.yml

Changes from 2.18.0

---

services/agents/proxysql.go
services/agents/proxysql_test.go

[PMM-8112](https://jira.percona.com/browse/PMM-8112)
https://github.com/percona/proxysql_exporter/pull/50
---

PMM-8112 Collect from stats_mysql_commands_counters

---

services/agents/postgresql.go
services/agents/postgresql_test.go

https://jira.percona.com/browse/PMM-8125
---

PMM-8125 Exclude Cloudsqladmin db

---

models/agent_model.go
models/agent_model_test.go

[PMM-8014](https://jira.percona.com/browse/PMM-8014)
https://github.com/percona/pmm-agent/pull/257
https://github.com/percona/pmm-admin/pull/155
---

PMM-8014 MySQL SSL refactor.

---

go.mod
go.sum
models/job_models.go
services/agents/jobs.go
services/agents/registry.go
services/management/backup/backups_service.go
services/management/backup/deps.go
services/management/backup/mock_jobs_service_test.go

[PMM-7568](https://jira.percona.com/browse/PMM-7568)
---
---

PMM-7568 MongoDB backup restores

---

.golangci.yml

https://golangci-lint.run/usage/linters/#godot

Add check for capital letter in comments

---

services/management/grpc/actions_server.go

fix the error message grammar

---

models/database.go

[PMM-8543](https://jira.percona.com/browse/PMM-8543)
---

PMM-8543 Fix artifacts migration

---

models/database.go

[PMM-8573](https://jira.percona.com/browse/PMM-8573)
---

PMM-8573 Fix migration.

---

main.go
utils/envvars/parser.go

[PMM-8709](https://jira.percona.com/browse/PMM-8709)
https://github.com/percona/pmm-ui-tests/pull/83
---

PMM-8709 Configurable version service URL.

---

services/agents/handler.go

[PMM-8421](https://jira.percona.com/browse/PMM-8421)
---

PMM-8421 Fix external listen port when pmm was upgraded.

---

services/agents/handler.go

* PMM-8421 Fix external listen port when pmm was upgraded.
* PMM-8421 Fix unhandled nil pointer.
[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)
---

PMM-8421 Fix external listen port when pmm was upgraded. (#820)

---

main.go
services/supervisord/supervisord.go

[PMM-8723](https://jira.percona.com/browse/PMM-8723)
---

PMM-8723 Restart dbaas-controller on startup

---

services/agents/handler.go

Changes from 2.22.0

---

api-tests/docker-compose.yml

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)
---

PMM-5106 Remove reference to PMM-5106

---

.github/workflows/ci.yml
CONTRIBUTING.md
Makefile.devcontainer
README.md
services/alertmanager/alertmanager.go

[PMM-6013](https://jira.percona.com/browse/PMM-6013)
---

PMM-6013 rename pmm-managed default branch

---

go.mod
go.sum
services/agents/vmagent.go
services/victoriametrics/prometheus.go
services/victoriametrics/scrape_configs.go
services/victoriametrics/victoriametrics_test.go

[PMM-9125](https://jira.percona.com/browse/PMM-9125)
---

PMM-9125 Enable stream parse only for postgres_exporter.

---

services/management/dbaas/kubernetes_server.go
services/management/dbaas/kubernetes_server_test.go
services/management/dbaas/psmdb_cluster_service_test.go
services/management/dbaas/xtradb_cluster_service_test.go

[PMM-8110](https://jira.percona.com/browse/PMM-8110)
---

PMM-8110 Don't install operators if they are existed.

---

api-tests/server/settings_test.go
models/settings_helpers.go
models/settings_helpers_test.go
services/server/server.go
services/server/server_test.go
utils/envvars/parser.go
utils/envvars/parser_test.go

[PMM-9086](https://jira.percona.com/browse/PMM-9086)
---

PMM-9086: Do not require Telemetry

---

.devcontainer/setup.py
api-tests/inventory/services_test.go
api-tests/management/postgresql_test.go
docker-compose.yml
models/database.go

[PMM-9155](https://jira.percona.com/browse/PMM-9155)
---

PMM-9155 fix failing tests

---

go.mod
go.sum
services/agents/vmagent.go
services/victoriametrics/prometheus.go
services/victoriametrics/scrape_configs.go
services/victoriametrics/victoriametrics_test.go

Changes from 2.24.0

---

api-tests/server/auth_test.go

[PMM-9050](https://jira.percona.com/browse/PMM-9050)
---

PMM-9050 Remove old API tests.

---

go.mod
services/telemetry/telemetry.go

[PMM-9280](https://jira.percona.com/browse/PMM-9280)
---

PMM-9280 Fix Time.

---

services/platform/platform.go
services/supervisord/supervisord.go
testdata/supervisord.d/grafana.ini
utils/envvars/parser.go
utils/envvars/parser_test.go
utils/saasreq/request.go

[PMM-9299](https://jira.percona.com/browse/PMM-9299)
---

PMM-9299 fix: add signout_redirect_url and increase timeout

---

services/platform/platform.go
services/supervisord/supervisord.go
testdata/supervisord.d/grafana.ini
utils/envvars/parser.go
utils/envvars/parser_test.go
utils/saasreq/request.go

This was merged into main in #950, we need this also in PMM 2.25.0 RC.
[PMM-9299](https://jira.percona.com/browse/PMM-9299)
---

PMM-9299 fix: add signout_redirect_url and increase timeout (#950)

---

services/agents/mongodb.go
services/agents/mongodb_test.go

**This is a cherry pick into pmm-2.25.0**
Already approved in https://github.com/percona/pmm-managed/pull/951
[PMM-9304](https://jira.percona.com/browse/PMM-9304) https://jira.percona.com/browse/PMM-9304

PMM-9304 Cherry pick on v2.25.0

---

api-tests/init.go
go.mod
go.sum

Fix we discussed on today's backend call.
---

Fix Connect API tests: add platformClient

---

go.mod
go.sum
models/agent_helpers.go
models/agent_helpers_test.go
models/agent_model.go
services/agents/mongodb.go
services/agents/mongodb_test.go
services/converters.go

[PMM-9246](https://jira.percona.com/browse/PMM-9246) Display Collstats Limit and Disabled collectors on Inventory

PMM-9246 Extended MongoDB message for inventory

---

go.mod
go.sum
models/agent_helpers.go
models/agent_helpers_test.go
models/agent_model.go
services/agents/mongodb.go
services/agents/mongodb_test.go
services/converters.go

Reverts percona/pmm-managed#955 since it wasn't released in 2.25.0

Revert "PMM-9246 Extended MongoDB message for inventory"

---

services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics_test.go

[PMM-8804](https://jira.percona.com/browse/PMM-8804)
---

PMM-8804 Remote PostgreSQL metrics are not being captured.

---

services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics_test.go

[PMM-9471](https://jira.percona.com/browse/PMM-9471)
---

PMM-9471 two resolutions for mongo db

---

services/victoriametrics/prometheus.go
services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics_test.go

PMM-9517
Build: SUBMODULES-2312

PMM-9517 Fix scrape configs for old mongodb_exporters.

---

services/agents/mongodb.go
services/agents/mongodb_test.go

PMM-9536
Build: SUBMODULES-2319

PMM-9536 enable indexstats and dbstats even for --collstats-limit=0.

---

.gitignore
go.mod
models/agent_model.go
services/agents/node.go
services/agents/node_test.go

Reverts percona/pmm-managed#989

Revert "PMM-9439 Added node_exporter tls config pass"

---

services/grafana/client_test.go

Fix tests after Grafana update

---

services/agents/mongodb.go
services/agents/mongodb_test.go
services/victoriametrics/prometheus.go
services/victoriametrics/scrape_configs.go
services/victoriametrics/scrape_configs_test.go
services/victoriametrics/victoriametrics_test.go

Pmm 2.26.0

---

.github/dependabot.yml

  Enable dependabot

---

services/victoriametrics/scrape_configs.go
services/victoriametrics/victoriametrics_test.go
testdata/victoriametrics/promscrape.base.yml
testdata/victoriametrics/promscrape.yml

PMM-9845
Build: SUBMODULES-2448

PMM-9845 Increase scrape config timeout.

---

api-tests/inventory/agents_test.go
api-tests/inventory/nodes_test.go
api-tests/inventory/services_test.go
api-tests/management/backup/backups_test.go
api-tests/management/backup/locations_test.go
api-tests/management/dbaas/kubernetes_server_test.go
api-tests/management/external_test.go
api-tests/management/haproxy_test.go
api-tests/management/helpers.go
api-tests/management/ia/channels_test.go
api-tests/management/ia/rules_test.go
api-tests/management/ia/templates_test.go
api-tests/management/mongodb_test.go
api-tests/management/mysql_test.go
api-tests/management/nodes_test.go
api-tests/management/postgresql_test.go
api-tests/management/proxysql_test.go
api-tests/server/checks_test.go
api-tests/server/helpers.go
go.mod
go.sum

PMM-7 Update pmm dependency

---

.github/workflows/ci.yml
services/victoriametrics/victoriametrics_test.go

PMM-9780 Update tests after VM update

---

go.mod
go.sum
services/checks/checks.go
services/checks/checks_test.go
services/types.go

PMM-9468
Build: SUBMODULES-2483

PMM-9468 Add metris queries support to advisors

---

.golangci-required.yml
.golangci.yml

[PMM-7](https://jira.percona.com/browse/PMM-7) - contributor may use forked pmm/API repository
Build: N/A - changes in linter specs

PMM-7 - Allowing to replace pmm module
